In [2]:
# Import PyTorch
import torch

In [5]:
# Create a 1D tensor
scalar = torch.tensor(5)
scalar

In [8]:
# Create a vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
# Look at the number of dimensions of a vector
vector.ndim

1

In [10]:
# Look at the shape of a vector
vector.shape

torch.Size([2])

In [11]:
# Look at the datatype of the elements in a vector
vector.dtype

torch.int64

In [12]:
# Create a matrix
matrix = torch.tensor([[10.0, 20.0],
                       [30.0, 40.0]])
matrix

tensor([[10., 20.],
        [30., 40.]])

In [13]:
# Look at properties of the matrix
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)

2
torch.Size([2, 2])
torch.float32


In [14]:
# Create a random matrix using .rand() or size=4x4
torch.rand(size=(4,4))

tensor([[0.4761, 0.9868, 0.6799, 0.2137],
        [0.1526, 0.9701, 0.6610, 0.4970],
        [0.9936, 0.9818, 0.4036, 0.9949],
        [0.3637, 0.2774, 0.5641, 0.8577]])

In [15]:
# Calculations using tensors
tensor = torch.tensor([1,2,3])
tensor + 20

tensor([21, 22, 23])

In [16]:
tensor * 10

tensor([10, 20, 30])

In [19]:
# Create two random tensors
tensor_1 = torch.tensor([[1,2,3],[2,3,4]])
tensor_2 = torch.tensor([[1,2],[2,3],[3,4]])

In [20]:
# Hadamard Product
    # Element-wise multiplication of two tensors
    # The two tensors must have the same shape
tensor_1 * tensor_1

tensor([[ 1,  4,  9],
        [ 4,  9, 16]])

In [21]:
# In the case of the dot product,
# the inner dimensions of the two 
# tensors must be the same
    # Example: tensor_1 = 2x3, tensor_2 = 3x2 
    # (inner dimensions are 3 and 3)

torch.matmul(tensor_1, tensor_2)

tensor([[14, 20],
        [20, 29]])

In [22]:
# The @ symbol can also be used for the dot product
tensor_1 @ tensor_2

tensor([[14, 20],
        [20, 29]])

### Tensor Indexing

In [23]:
indexing_example = torch.tensor([[10,20,30],
                                 [40,50,60],
                                 [70,80,90]])
indexing_example

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [24]:
# Index first row
indexing_example[0,:]

tensor([10, 20, 30])

In [25]:
# Index first column
indexing_example[:,0]

tensor([10, 40, 70])

In [26]:
# Indexing 3D tensor
indexing_example_3d = torch.tensor([[[10,20,30],
                                     [40,50,60],
                                     [70,80,90]],
                                    [[100,200,300],
                                     [400,500,600],
                                     [700,800,900]]])
indexing_example_3d

tensor([[[ 10,  20,  30],
         [ 40,  50,  60],
         [ 70,  80,  90]],

        [[100, 200, 300],
         [400, 500, 600],
         [700, 800, 900]]])

In [27]:
# extract '100' from tensor
    # First Row
    # First Column
    # Second Matrix
indexing_example_3d[1,0,0]

tensor(100)